### ISSUE TITLE
Maybe you made an error ?

### ISSUE THREAD

**Issue by KennnyTroll** [LeClubSandwichStudio/MUR#3]
Hello!
Maybe you made an error on V0.1 the last argument in the Adafruit_BME280 function
bmePatient.setSampling (1, 1, 3, 1, 1, 10);
and
bmeAmbient.setSampling (1, 1, 3, 1, 1, 10);
because I had to make a modification in your code to bring it to Visual Studio
bmePatient.setSampling (1, 1, 3, 1, 1, 6);
bmeAmbient.setSampling (1, 1, 3, 1, 1, 6);

and visual studio do not accept int values for the setSampling function

I had to replace with

.setSampling (
      Adafruit_BME280 :: sensor_mode :: MODE_FORCED ,// = 1
      Adafruit_BME280 :: sensor_sampling :: SAMPLING_X1 ,// = 1
      Adafruit_BME280 :: sensor_sampling :: SAMPLING_X4 ,// = 3
      Adafruit_BME280 :: sensor_sampling :: SAMPLING_X1 ,// = 1
      Adafruit_BME280 :: sensor_filter :: FILTER_X2 ,// = 1
      Adafruit_BME280 :: standby_duration :: STANDBY_MS_10 //STANDBY_MS_10 = 6      10 not exists !!
      );

For information:
enum standby_duration {
    STANDBY_MS_0_5 = 0b000, // = 0
    STANDBY_MS_10 = 0b110, // = 6
    STANDBY_MS_20 = 0b111, // = 7
    STANDBY_MS_62_5 = 0b001, // = 1
    STANDBY_MS_125 = 0b010, // = 2
    STANDBY_MS_250 = 0b011, // = 3
    STANDBY_MS_500 = 0b100, // = 4
    STANDBY_MS_1000 = 0b101 // = 5
  };

I hope I'm not mistaken, and that it helps you ...

I do not yet have a BME280 sensor to try this code at home but I am trying to create a U-tube manometers with salt water ...

Good luck to all! And thanks for everything !

**Comment by fpistm** [comment]
Hi, 
I confirm the issue raised by @KennnyTroll.
Using enum type is better to ensure to not use a wrong value which is the case here.

**Comment by LeSuedois** [comment]
Thank you guys, indeed I did a mistake...
I try to check this out this afternoon, but most time this week was spent to sourcing parts and talking to people.....
We are in  a hurry since 3 weeks and it's clear that no one in this wokshop is a professional embedded software developer. I only do stuff that works (search for "lesuedois" on google)..
Please feel free to do a pull request if you see stuff I messed up!
This is IMO the fastest way to help me!
Thank you!

**Comment by KennnyTroll** [comment]
Pull requests sent !
